---
title: "L227 MyLake Phytoplankton Analysis"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Working directory should be source file location
getwd()

library(tidyverse)
library(lubridate)
library(hydroGOF)


theme_std <- function (base_size = 11, base_family = "") {
  theme_grey(base_size = base_size, base_family = base_family) %+replace% 
    theme(axis.ticks = element_line(colour = "black", size = 1), 
          legend.key = element_rect(colour = "white"), 
          panel.background = element_rect(fill = "white", colour = NA), 
          panel.border = element_rect(fill = NA, colour = NA),
          axis.line = element_line(size = 0.5, colour = "black"),
          panel.grid.major = element_line(NA), 
          panel.grid.minor = element_line(NA), 
          strip.background = element_rect(fill = "grey80", colour = "grey50", size = 0.2),
          axis.text  = element_text(size=rel(0.9)),
          axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"),size=rel(1)),
          axis.title.y = element_text(margin = unit(c(0, 3, 0, 0), "mm"),size=rel(1), angle = 90),
          strip.text = element_text(size = rel(1.15), colour = "black", face = "bold"),
          plot.margin=unit(c(10,10,10,10),"pt"))}
theme_set(theme_std())



```

## Wrangling
```{r}

# Observation file
phyto.obs <- read.csv("OutputForOptimization_Phyto.csv")

# Output file
phyto.out <- read.csv("Output_IntegratedEpi_Phyto.csv")

# Observation file
phyto.obs$date <- as.Date(phyto.obs$date, "%Y-%m-%d")

phyto.obs <- phyto.obs %>%
  filter(date > as.Date("1969-06-26"))

# Output file
colnames(phyto.out) <- c("Year", "Month", "Day", "diazoPP", "nondiazoPP")
phyto.out <- phyto.out %>%
  unite(date, Year, Month, Day, sep = '-')
phyto.out$date <- as.Date(phyto.out$date, "%Y-%m-%d")
phyto.out <- phyto.out %>%
  mutate(DOY = yday(date))

phyto.out.summary <- phyto.out %>%
  mutate(Year = year(date), 
         Period = ifelse(Year < 1975, "High N:P", ifelse(Year > 1989, "P only", "Low N:P")), 
         diazoprop = diazoPP/(diazoPP + nondiazoPP)) %>%
  filter(DOY > 105 & DOY < 305 & Year > 1969) %>%
  group_by(Period, DOY) %>%
  summarise(n = sum(complete.cases(diazoprop)),
            diazo.mean = mean(diazoprop), 
            diazo.sd = sd(diazoprop), 
            margin = qnorm(0.975) * diazo.sd/sqrt(n), 
            upperCI = diazo.mean + margin,
            lowerCI = diazo.mean - margin)

phyto.obs.summary <- phyto.obs %>%
  mutate(week = week(date),
         Period = ifelse(Year < 1975, "High N:P", ifelse(Year > 1989, "P only", "Low N:P")), 
         diazoprop = diazoPP/(diazoPP + nondiazoPP)) %>%
  group_by(Period, week) %>%
  summarise(n = sum(complete.cases(diazoprop)),
            diazo.mean = mean(diazoprop), 
            diazo.sd = sd(diazoprop), 
            margin = qnorm(0.975) * diazo.sd/sqrt(n), 
            upperCI = diazo.mean + margin,
            lowerCI = diazo.mean - margin)


# Join files
phyto.match <- left_join(phyto.obs, phyto.out, by = "date")

phyto.match <- phyto.match %>%
  mutate(diazoprop.obs = diazoPP.x/(diazoPP.x + nondiazoPP.x),
         nondiazoprop.obs = nondiazoPP.x/(diazoPP.x + nondiazoPP.x),
         diazoprop.mod = diazoPP.y/(diazoPP.y + nondiazoPP.y),
         nondiazoprop.mod = nondiazoPP.y/(diazoPP.y + nondiazoPP.y),
         Period = ifelse(Year < 1975, "High N:P", ifelse(Year > 1989, "P only", "Low N:P")))

```

## Visualizations
```{r}
PPmodelplot <- ggplot(phyto.out) +
  #geom_rect(xmin = -Inf, xmax = as.numeric(as.Date("1975-01-01")), ymin = -Inf, ymax = Inf, fill = "gray90") +
  #geom_rect(xmin = as.numeric(as.Date("1990-01-01")), xmax = Inf, ymin = -Inf, ymax = Inf, fill = "gray90") +
  geom_line(data = phyto.out, aes(x = date, y = diazoPP, color = "out.diazo"), size = 0.5) +
  geom_line(data = phyto.out, aes(x = date, y = nondiazoPP, color = "out.nondiazo"), size = 0.5) +
  geom_point(data = phyto.obs, aes(x = date, y = diazoPP, color = "obs.diazo"), pch = 19, size = 0.75) +
  geom_point(data = phyto.obs, aes(x = date, y = nondiazoPP, color = "obs.nondiazo"), pch = 19, size = 0.75) +
  ylab(expression(PP ~ (mu*g / L))) +
  xlab(" ") +
  ylim(0, 50) +
  scale_colour_manual("", breaks = c("out.diazo", "out.nondiazo", "obs.diazo", "obs.nondiazo"), 
                      values = c("#d14a42ff",  "#240c4cff", "#d14a42ff",  "#240c4cff")) +
  theme(legend.position = "top", plot.margin=unit(c(0, 0.1, -0.25, 0), "cm"), 
        legend.key.size = unit(0.1, "cm")) 
print(PPmodelplot)

PPfitplot <- ggplot(phyto.match) +
  geom_point(aes(x = nondiazoPP.x, y = nondiazoPP.y), color = "#240c4cff") +
  geom_point(aes(x = diazoPP.x, y = diazoPP.y), color = "#d14a42ff") +
  geom_abline(slope = 1, intercept = 0) +
  ylab(expression(modeled ~ PP ~ (mu*g / L))) +
  xlab(expression(observed ~ PP ~ (mu*g / L))) +
  scale_colour_manual("", breaks = c("diazo", "nondiazo"), values = c("#d14a42ff",  "#240c4cff")) 
print(PPfitplot)

diazopropplot <- ggplot(phyto.match, 
                        aes(x = diazoprop.obs, y = diazoprop.mod, color = Period)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0)
print(diazopropplot)

nondiazopropplot <- ggplot(phyto.match, 
                        aes(x = nondiazoprop.obs, y = nondiazoprop.mod, color = Month)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0)
print(nondiazopropplot)


ggplot(phyto.out.summary, aes(x = DOY, y = diazo.mean)) +
  geom_line(aes(color = Period)) +
  geom_ribbon(aes(ymin = lowerCI, ymax = upperCI, fill = Period), alpha = 0.2) +
  scale_color_manual(values = c("#f99d15ff", "#d14a42ff", "#240c4cff")) +
  scale_fill_manual(values = c("#f99d15ff", "#d14a42ff", "#240c4cff"))

ggplot(phyto.obs.summary, aes(x = week, y = diazo.mean)) +
  geom_line(aes(color = Period)) +
  geom_ribbon(aes(ymin = lowerCI, ymax = upperCI, fill = Period), alpha = 0.2) +
  #geom_line(data = phyto.out.summary, aes(x = week, y = diazo.mean, color = Period), lty = 2) +
  scale_color_manual(values = c("#f99d15ff", "#d14a42ff", "#240c4cff")) +
  scale_fill_manual(values = c("#f99d15ff", "#d14a42ff", "#240c4cff"))

```

## Fit tests
```{r}
nondiazoPP.regression <- lm(phyto.match$nondiazoPP.x ~ phyto.match$nondiazoPP.y)
summary(nondiazoPP.regression)$adj.r.squared
mse.nondiazoPP <- mean(residuals(nondiazoPP.regression)^2); rmse.nondiazoPP <- sqrt(mse.nondiazoPP); rmse.nondiazoPP
rmse.nondiazoPP/sd(na.omit(phyto.match$nondiazoPP.x))
NashSutcliffe.nondiazoPP <- NSE(phyto.match$nondiazoPP.y, phyto.match$nondiazoPP.x); NashSutcliffe.nondiazoPP

diazoPP.regression <- lm(phyto.match$diazoPP.x ~ phyto.match$diazoPP.y)
summary(diazoPP.regression)$adj.r.squared
mse.diazoPP <- mean(residuals(diazoPP.regression)^2); rmse.diazoPP <- sqrt(mse.diazoPP); rmse.diazoPP
rmse.diazoPP/sd(na.omit(phyto.match$diazoPP.x))
NashSutcliffe.diazoPP <- NSE(phyto.match$diazoPP.y, phyto.match$diazoPP.x); NashSutcliffe.diazoPP

nondiazoPP.regression <- lm(phyto.match$nondiazoPP.x[phyto.match$Year < 1975] ~ phyto.match$nondiazoPP.y[phyto.match$Year < 1975])
summary(nondiazoPP.regression)$adj.r.squared
mse.nondiazoPP <- mean(residuals(nondiazoPP.regression)^2); rmse.nondiazoPP <- sqrt(mse.nondiazoPP); rmse.nondiazoPP
rmse.nondiazoPP/sd(na.omit(phyto.match$nondiazoPP.x[phyto.match$Year < 1975]))
NashSutcliffe.nondiazoPP <- NSE(phyto.match$nondiazoPP.y[phyto.match$Year < 1975], phyto.match$nondiazoPP.x[phyto.match$Year < 1975]); NashSutcliffe.nondiazoPP

diazoPP.regression <- lm(phyto.match$diazoPP.x[phyto.match$Year < 1975] ~ phyto.match$diazoPP.y[phyto.match$Year < 1975])
summary(diazoPP.regression)$adj.r.squared
mse.diazoPP <- mean(residuals(diazoPP.regression)^2); rmse.diazoPP <- sqrt(mse.diazoPP); rmse.diazoPP
rmse.diazoPP/sd(na.omit(phyto.match$diazoPP.x[phyto.match$Year < 1975]))
NashSutcliffe.diazoPP <- NSE(phyto.match$diazoPP.y[phyto.match$Year < 1975], phyto.match$diazoPP.x[phyto.match$Year < 1975]); NashSutcliffe.diazoPP

nondiazoPP.regression <- lm(phyto.match$nondiazoPP.x[phyto.match$Year > 1974 & phyto.match$Year < 1990] ~ phyto.match$nondiazoPP.y[phyto.match$Year > 1974 & phyto.match$Year < 1990])
summary(nondiazoPP.regression)$adj.r.squared
mse.nondiazoPP <- mean(residuals(nondiazoPP.regression)^2); rmse.nondiazoPP <- sqrt(mse.nondiazoPP); rmse.nondiazoPP
rmse.nondiazoPP/sd(na.omit(phyto.match$nondiazoPP.x[phyto.match$Year > 1974 & phyto.match$Year < 1990]))
NashSutcliffe.nondiazoPP <- NSE(phyto.match$nondiazoPP.y[phyto.match$Year > 1974 & phyto.match$Year < 1990], phyto.match$nondiazoPP.x[phyto.match$Year > 1974 & phyto.match$Year < 1990]); NashSutcliffe.nondiazoPP

diazoPP.regression <- lm(phyto.match$diazoPP.x[phyto.match$Year > 1974 & phyto.match$Year < 1990] ~ phyto.match$diazoPP.y[phyto.match$Year > 1974 & phyto.match$Year < 1990])
summary(diazoPP.regression)$adj.r.squared
mse.diazoPP <- mean(residuals(diazoPP.regression)^2); rmse.diazoPP <- sqrt(mse.diazoPP); rmse.diazoPP
rmse.diazoPP/sd(na.omit(phyto.match$diazoPP.x[phyto.match$Year > 1974 & phyto.match$Year < 1990]))
NashSutcliffe.diazoPP <- NSE(phyto.match$diazoPP.y[phyto.match$Year > 1974 & phyto.match$Year < 1990], phyto.match$diazoPP.x[phyto.match$Year > 1974 & phyto.match$Year < 1990]); NashSutcliffe.diazoPP

nondiazoPP.regression <- lm(phyto.match$nondiazoPP.x[phyto.match$Year > 1989] ~ phyto.match$nondiazoPP.y[phyto.match$Year > 1989])
summary(nondiazoPP.regression)$adj.r.squared
mse.nondiazoPP <- mean(residuals(nondiazoPP.regression)^2); rmse.nondiazoPP <- sqrt(mse.nondiazoPP); rmse.nondiazoPP
rmse.nondiazoPP/sd(na.omit(phyto.match$nondiazoPP.x[phyto.match$Year > 1989]))
NashSutcliffe.nondiazoPP <- NSE(phyto.match$nondiazoPP.y[phyto.match$Year > 1989], phyto.match$nondiazoPP.x[phyto.match$Year > 1989]); NashSutcliffe.nondiazoPP

diazoPP.regression <- lm(phyto.match$diazoPP.x[phyto.match$Year > 1989] ~ phyto.match$diazoPP.y[phyto.match$Year > 1989])
summary(diazoPP.regression)$adj.r.squared
mse.diazoPP <- mean(residuals(diazoPP.regression)^2); rmse.diazoPP <- sqrt(mse.diazoPP); rmse.diazoPP
rmse.diazoPP/sd(na.omit(phyto.match$diazoPP.x[phyto.match$Year > 1989]))
NashSutcliffe.diazoPP <- NSE(phyto.match$diazoPP.y[phyto.match$Year > 1989], phyto.match$diazoPP.x[phyto.match$Year > 1989]); NashSutcliffe.diazoPP

```

